
DROP TABLE IF EXISTS ingestao_log CASCADE;
DROP TABLE IF EXISTS raw_ingestao CASCADE;
DROP TABLE IF EXISTS suspeitas CASCADE;
DROP TABLE IF EXISTS sancoes CASCADE;
DROP TABLE IF EXISTS empresas CASCADE;
DROP TABLE IF EXISTS despesas CASCADE;
DROP TABLE IF EXISTS parlamentares CASCADE;
