

ALTER TABLE suspeitas ADD COLUMN IF NOT EXISTS validada_por VARCHAR(100);
ALTER TABLE suspeitas ADD COLUMN IF NOT EXISTS validada_em TIMESTAMPTZ;
ALTER TABLE suspeitas ADD COLUMN IF NOT EXISTS feedback TEXT;
