-- Rollback Maracatu UUID retrofit P2 / Stage D (independent leaves cutover).
--
-- IRREVERSIBLE for the four SERIAL/BIGSERIAL leaves (glossario_termos, candidatos_tse,
-- ingestao_log, raw_ingestao): the apply migration DROPped the int id column, which also
-- dropped its sequence. The original integer ids cannot be regenerated by SQL. To recover
-- a committed-but-bad P2, restore the pre-window backup instead of running this rollback:
--   make restore FILE=<pre-window backup>
-- (the retrofit window verifies `make backup` is restorable before this apply runs).
--
-- The statements below reverse ONLY the part that is structurally reversible without data
-- loss: orgaos_federais, whose apply step dropped no data column (it only re-pointed the
-- PK from codigo to the new id). Demote id back to a plain UNIQUE NOT NULL, restore the
-- PRIMARY KEY on codigo, and rename id -> id_uuid so the table matches its post-Stage-A
-- (post-0018) shape again.

ALTER TABLE orgaos_federais DROP CONSTRAINT orgaos_federais_pkey;
ALTER TABLE orgaos_federais RENAME COLUMN id TO id_uuid;
ALTER TABLE orgaos_federais ADD CONSTRAINT orgaos_federais_id_uuid_key UNIQUE (id_uuid);
ALTER TABLE orgaos_federais ALTER COLUMN id_uuid SET NOT NULL;
ALTER TABLE orgaos_federais DROP CONSTRAINT orgaos_federais_codigo_key;
ALTER TABLE orgaos_federais ADD PRIMARY KEY (codigo);

-- glossario_termos, candidatos_tse, ingestao_log, raw_ingestao: NOT reversible here.
-- Recover via `make restore FILE=<pre-window backup>` (see header).
